### ISSUE TITLE
I can not fix this issue

### ISSUE THREAD

**Issue by asharafkar** [saulmm/Android-Material-Example#1]
11-25 12:34:44.101  30662-30662/com.saulmm.material.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.saulmm.material.myapplication, PID: 30662
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saulmm.material.myapplication/com.saulmm.material.activities.DialerSampleActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:147)
            at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:139)
            at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
            at com.saulmm.material.activities.DialerSampleActivity.onCreate(DialerSampleActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5426)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by clxxxii** [comment]
How can I use this app on a Samsung Galaxy S5? When I set minSdkVersion to 19 the app immediately crashes, when I change it to 21, I receive this error: 

pkg: /data/local/tmp/com.saulmm.material.myapplication
Failure [INSTALL_FAILED_OLDER_SDK]

**Comment by asharafkar** [comment]
Hi, please leave your crash log...

**Comment by clxxxii** [comment]
Hey man!


Do you work for Google? Who do you work for to know so much about material
design? How many years have you been coding?


This is the way you have it regularly.


Here's the issue:


Waiting for device.

Target device: samsung-samsung_sm_g900a-9d9796ee

Uploading file

local path:
/Users/clxxxii/Downloads/Android-Material-Examples-master/app/build/outputs/apk/app-debug.apk

remote path: /data/local/tmp/com.saulmm.material.myapplication

Installing com.saulmm.material.myapplication

DEVICE SHELL COMMAND: pm install -r
"/data/local/tmp/com.saulmm.material.myapplication"

pkg: /data/local/tmp/com.saulmm.material.myapplication

Failure [INSTALL_FAILED_OLDER_SDK]



When I change this:  minSdkVersion 19 , I get these errors.


03-23 16:07:29.552  29884-29884/com.saulmm.material.myapplication
E/AndroidRuntime﹕ FATAL EXCEPTION: main

    Process: com.saulmm.material.myapplication, PID: 29884

    java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.saulmm.material.myapplication/com.saulmm.material.activities.TransitionFirstActivity}:
android.view.InflateException: Binary XML file line #9: Error inflating
class android.view.View

            at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)

            at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2582)

            at
android.app.ActivityThread.access$900(ActivityThread.java:174)

            at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)

            at android.os.Handler.dispatchMessage(Handler.java:102)

            at android.os.Looper.loop(Looper.java:146)

            at android.app.ActivityThread.main(ActivityThread.java:5731)

            at java.lang.reflect.Method.invokeNative(Native Method)

            at java.lang.reflect.Method.invoke(Method.java:515)

            at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)

            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)

            at dalvik.system.NativeStart.main(Native Method)

     Caused by: android.view.InflateException: Binary XML file line #9:
Error inflating class android.view.View

            at
android.view.LayoutInflater.createView(LayoutInflater.java:626)

            at
android.view.LayoutInflater.onCreateView(LayoutInflater.java:658)

            at
com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)

            at
android.view.LayoutInflater.onCreateView(LayoutInflater.java:675)

            at
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)

            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)

            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)

            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)

            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)

            at
com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:352)

            at android.app.Activity.setContentView(Activity.java:2057)

            at
com.saulmm.material.activities.TransitionFirstActivity.onCreate(TransitionFirstActivity.java:23)

            at android.app.Activity.performCreate(Activity.java:5580)

            at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)

            at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2487)

            at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2582)

            at
android.app.ActivityThread.access$900(ActivityThread.java:174)

            at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)

            at android.os.Handler.dispatchMessage(Handler.java:102)

            at android.os.Looper.loop(Looper.java:146)

            at android.app.ActivityThread.main(ActivityThread.java:5731)

            at java.lang.reflect.Method.invokeNative(Native Method)

            at java.lang.reflect.Method.invoke(Method.java:515)

            at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)

            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)

            at dalvik.system.NativeStart.main(Native Method)

     Caused by: java.lang.reflect.InvocationTargetException

            at java.lang.reflect.Constructor.constructNative(Native Method)

            at
java.lang.reflect.Constructor.newInstance(Constructor.java:423)

            at
android.view.LayoutInflater.createView(LayoutInflater.java:600)

            at
android.view.LayoutInflater.onCreateView(LayoutInflater.java:658)

            at



When i change this:  compileSdkVersion 19 I get these errors.


/Users/clxxxii/Downloads/Android-Material-Examples-master/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v11/values.xml

Error:(47, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(47, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(47, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(47, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

/Users/clxxxii/Downloads/Android-Material-Examples-master/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v14/values.xml

Error:(17, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(17, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(17, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

Error:(17, 21) No resource found that matches the given name: attr
'android:actionModeShareDrawable'.

/Users/clxxxii/Downloads/Android-Material-Examples-master/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/values-v21/values.xml

Error:(1) Error retrieving parent for item: No resource found that matches
the given name 'android:TextAppearance.Material'.

Error:(1) Error retrieving parent for item: No resource found that matches
the given name 'android:TextAppearance.Material.Body1'.

Error:(1) Error retrieving parent for item: No resource found that matches
the given name 'android:TextAppearance.Material.Body2'.

Error:(1) Error retrieving parent for item: No resource found that matches
the given name 'android:TextAppearance.Material.Button'.

**Comment by asharafkar** [comment]
Ummm; using Android studio or Eclipse?

Please update your appcompat v7 at SDK manager and gradle file to last
version.

**Comment by clxxxii** [comment]
I'm using both.. I prefer Eclipse but people are saying I should use
Android Studio. I need to check what version my appcompat v7 and grade
file. I think they're at their latest version.

**Comment by asharafkar** [comment]
Please open your android SDK manager and update support library v7 to last
version. OK?

**Comment by clxxxii** [comment]
I have Android Support Library, revision 22.

**Comment by clxxxii** [comment]
![screen shot 2015-03-24 at 9 45 08 am](https://cloud.githubusercontent.com/assets/11335498/6802953/b8fd829a-d20a-11e4-953d-373cbce2eb41.png)

**Comment by asharafkar** [comment]
Please investigate this link:

http://stackoverflow.com/questions/4512981/android-view-inflateexception-binary-xml-file-line-12-error-inflating-class
